site_name: LeeYeung

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs #导航栏
    - navigation.path #启用导航路径
#    - toc.integrate #启用锚点跟踪
    - toc.follow #启用侧边栏自动滚动
    - navigation.top #返回顶部按钮
    - contentFile.tabs.link #生成链接
    - contentFile.code.copy #代码块复制
    - contentFile.code.annotate #代码注释
    - navigation.footer
  icon:
    repo: fontawesome/brands/github
    annotation: material/plus-circle
  logo: img/logo.jpg
  favicon: img/favicon.ico
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

#    primary: white

#    accent: blue
     
      # Palette toggle for light mode


#  name: readthedocs
#  name: cluster
nav:
  - 首页: index.md
  - 更多:
    - 基本劳动法: contentFile/index.md
  - 结尾: about/index.md
  - 博文:
    - 杂想: blog/index.md
#  - Page: example/page.md

plugins:
#  - material/meta
#  - mkdocs-jupyter:

  - search
  - tags
  - blog:
      blog_dir: blog
      blog_toc: true
      post_date_format: full

repo_url: https://github.com/LeeYeungYeung/law.git
repo_name: github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LeeYeungYeung/LeeYeungYeung.git/



markdown_extensions:
  - attr_list #
  - md_in_html #启用html 中的mkdoc
  - pymdownx.superfences
  - admonition  # 配置启用告诫
  - pymdownx.details #配置启用告诫
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - pymdownx.emoji: #使用表情
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables #启用数据表